### ISSUE TITLE
用插件形式安装出现错误

### ISSUE THREAD

**Issue by tin8** [Yabandpay/magento2.3#1]
测试环境：
CENTOS 8 / CENTOS 6.10 
NGINX :1.61
MYSQL: 5.7
PHP: 7.3.15
用插件的方式进行安装，因为composer require yabandpay/magento2.2 太久。
出现如下错误：

PHP Fatal error:  Uncaught Error: Class 'YaBandPay\Api\Payment' not found in /data/wwwroot/www/app/code/YaBandPay/Payment/Setup/InstallData.php:52
Stack trace:
#0 /data/wwwroot/www/setup/src/Magento/Setup/Model/Installer.php(987): YaBandPay\Payment\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#1 /data/wwwroot/www/setup/src/Magento/Setup/Model/Installer.php(879): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data', Array)
#2 /data/wwwroot/www/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(123): Magento\Setup\Model\Installer->installDataFixtures(Array)
#3 /data/wwwroot/www/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /data/wwwroot/www/vendor/symfony/console/Application.php(893): Symfony\Component\ in /data/wwwroot/www/app/code/YaBandPay/Payment/Setup/InstallData.php on line 52
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/1001571697740"}]}}

**Comment by Yabandpay** [comment]
您好！
请加我们技术微信 robinbai1020




 
 
Haibo Feng
CEO
Mobile: +31 6 8489 9888
Phone: +31 70 221 0801
Website: www.yabandmedia.com
Address: Laan van Vredenoord 33
2289 DA Rijswijk, the Netherlands
 
发件人： tin8
发送时间： 2020-03-21 06:03
收件人： Yabandpay/magento2.3
抄送： Subscribed
主题： [Yabandpay/magento2.3] 用插件形式安装出现错误 (#1)
测试环境：
CENTOS 8 / CENTOS 6.10
NGINX :1.61
MYSQL: 5.7
PHP: 7.3.15
用插件的方式进行安装，因为composer require yabandpay/magento2.2 太久。
出现如下错误：
PHP Fatal error: Uncaught Error: Class 'YaBandPay\Api\Payment' not found in /data/wwwroot/www/app/code/YaBandPay/Payment/Setup/InstallData.php:52
Stack trace:
#0 /data/wwwroot/www/setup/src/Magento/Setup/Model/Installer.php(987): YaBandPay\Payment\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#1 /data/wwwroot/www/setup/src/Magento/Setup/Model/Installer.php(879): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data', Array)
#2 /data/wwwroot/www/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(123): Magento\Setup\Model\Installer->installDataFixtures(Array)
#3 /data/wwwroot/www/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /data/wwwroot/www/vendor/symfony/console/Application.php(893): Symfony\Component\ in /data/wwwroot/www/app/code/YaBandPay/Payment/Setup/InstallData.php on line 52
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api/1001571697740"}]}}
